---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pg-crd
  namespace: confluent
spec:
  class: "io.debezium.connector.postgresql.PostgresConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    "database.hostname": "10.0.1.37"
    "database.port": "5432"
    "database.user": "myuser"
    "database.password": "mypassword"
    "database.dbname" : "postgres"
    "database.server.name": "asgard"
    "transforms": "addTopicSuffix"
    "transforms.addTopicSuffix.type": "org.apache.kafka.connect.transforms.RegexRouter"
    "transforms.addTopicSuffix.regex": "(.*)"
    "transforms.addTopicSuffix.replacement": "$1-x-raw"