---
version: '3.5'
services:

  postgres:
    image: debezium/postgres:10
    hostname: postgres
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
      - ./customers.sql:/docker-entrypoint-initdb.d/z99_dump.sql